---
theme: jekyll-theme-minimal
title: Aravinda Kanchana Ruwanpathirana
logo: "/img/profile.jpg"
---
<!DOCTYPE html>
<!-- saved from url=(0029)https://kanchanarp.github.io/ -->
<html lang="en-US" class="gr__kanchanarp_github_io"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Begin Jekyll SEO tag v2.5.0 -->
<title>Aravinda Kanchana Ruwanpathirana</title>
<meta name="generator" content="Jekyll v3.7.4">
<meta property="og:title" content="About Me">
<meta property="og:locale" content="en_US">
<meta name="description" content="Personal Webpage">
<meta property="og:description" content="Personal Webpage">
<link rel="canonical" href="https://kanchanarp.github.io/">
<meta property="og:url" content="https://kanchanarp.github.io/">
<meta property="og:site_name" content="Aravinda Kanchana Ruwanpathirana">
<script type="application/ld+json">
{"@type":"WebSite","headline":"About Me","url":"https://kanchanarp.github.io/","name":"Aravinda Kanchana Ruwanpathirana","publisher":{"@type":"Organization","logo":{"@type":"ImageObject","url":"https://kanchanarp.github.io/img/profile.jpg"}},"description":"Personal Webpage","@context":"http://schema.org"}</script>
<!-- End Jekyll SEO tag -->

    <link rel="stylesheet" href="./About Me _ Aravinda Kanchana Ruwanpathirana_files/style.css">
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
  </head>
  <body data-gr-c-s-loaded="true">
    <div class="wrapper">
      <header>
        <h1><a href="https://kanchanarp.github.io/">Aravinda Kanchana Ruwanpathirana</a></h1>
        
        
          <img src="./About Me _ Aravinda Kanchana Ruwanpathirana_files/profile.jpg" alt="Logo" style="border-radius: 25px">
        

        <p>Personal Webpage</p>

        

        
        <p class="view"><a href="https://github.com/kanchanarp">View My GitHub Profile</a></p>
        

        
      </header>
      <section>

      <h2 id="about-me">About Me</h2>

<p>I am a first year PhD student at the School of Computing at University of Utah.</p>

<h2 id="education">Education</h2>

<p>Markdown is a lightweight and easy-to-use syntax for styling your writing. It includes conventions for</p>

<h2 id="work-experience">Work Experience</h2>

<p>Markdown is a lightweight and easy-to-use syntax for styling your writing. It includes conventions for</p>

<h2 id="publications">Publications</h2>

<div class="language-markdown highlighter-rouge"><div class="highlight"><pre class="highlight"><code>Syntax highlighted code block

<span class="gh"># Header 1</span>
<span class="gu">## Header 2</span>
<span class="gu">### Header 3</span>
<span class="p">
-</span> Bulleted
<span class="p">-</span> List
<span class="p">
1.</span> Numbered
<span class="p">2.</span> List

<span class="gs">**Bold**</span> and _Italic_ and <span class="sb">`Code`</span> text

<span class="p">[</span><span class="nv">Link</span><span class="p">](</span><span class="sx">url</span><span class="p">)</span> and !<span class="p">[</span><span class="nv">Image</span><span class="p">](</span><span class="sx">src</span><span class="p">)</span>
</code></pre></div></div>

<p>For more details see <a href="https://guides.github.com/features/mastering-markdown/">GitHub Flavored Markdown</a>.</p>

<h3 id="jekyll-themes">Jekyll Themes</h3>

<p>Your Pages site will use the layout and styles from the Jekyll theme you have selected in your <a href="https://github.com/kanchanarp/kanchanarp.github.io/settings">repository settings</a>. The name of this theme is saved in the Jekyll <code class="highlighter-rouge">_config.yml</code> configuration file.</p>

<h3 id="support-or-contact">Support or Contact</h3>

<p>Having trouble with Pages? Check out our <a href="https://help.github.com/categories/github-pages-basics/">documentation</a> or <a href="https://github.com/contact">contact support</a> and we’ll help you sort it out.</p>


      </section>
      <footer>
        
        <p><small>Hosted on GitHub Pages — Theme by <a href="https://github.com/orderedlist">orderedlist</a></small></p>
      </footer>
    </div>
    <script src="./About Me _ Aravinda Kanchana Ruwanpathirana_files/scale.fix.js.download"></script>
    
  

</body></html>
